/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GovernanceRegistry {
  export type ProposalStruct = {
    proposalId: string;
    contentHash: string;
    proposerUserId: string;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type ProposalStructOutput = [
    proposalId: string,
    contentHash: string,
    proposerUserId: string,
    votesFor: bigint,
    votesAgainst: bigint,
    createdAt: bigint,
    deadline: bigint,
    status: bigint,
    exists: boolean
  ] & {
    proposalId: string;
    contentHash: string;
    proposerUserId: string;
    votesFor: bigint;
    votesAgainst: bigint;
    createdAt: bigint;
    deadline: bigint;
    status: bigint;
    exists: boolean;
  };
}

export interface GovernanceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assignRole"
      | "createProposal"
      | "elder"
      | "elderVoteWeight"
      | "finalizeProposal"
      | "getProposal"
      | "getRole"
      | "hasVoted"
      | "proposals"
      | "quorumThreshold"
      | "roles"
      | "totalMembers"
      | "totalProposals"
      | "transferEldership"
      | "userIds"
      | "veto"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EldershipTransferred"
      | "ProposalApproved"
      | "ProposalCreated"
      | "ProposalFinalized"
      | "ProposalVetoed"
      | "RoleAssigned"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "elder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "elderVoteWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeProposal",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getProposal", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "proposals", values: [string]): string;
  encodeFunctionData(
    functionFragment: "quorumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "roles", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "totalMembers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferEldership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "veto",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "elder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "elderVoteWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "roles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferEldership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "veto", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace EldershipTransferredEvent {
  export type InputTuple = [
    oldElder: AddressLike,
    newElder: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldElder: string,
    newElder: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldElder: string;
    newElder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalApprovedEvent {
  export type InputTuple = [
    proposalId: string,
    votesFor: BigNumberish,
    votesAgainst: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    votesFor: bigint,
    votesAgainst: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    votesFor: bigint;
    votesAgainst: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: string,
    contentHash: string,
    proposerUserId: string,
    deadline: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    contentHash: string,
    proposerUserId: string,
    deadline: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    contentHash: string;
    proposerUserId: string;
    deadline: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalFinalizedEvent {
  export type InputTuple = [proposalId: string, timestamp: BigNumberish];
  export type OutputTuple = [proposalId: string, timestamp: bigint];
  export interface OutputObject {
    proposalId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalVetoedEvent {
  export type InputTuple = [
    proposalId: string,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [
    account: AddressLike,
    userId: string,
    role: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    userId: string,
    role: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    account: string;
    userId: string;
    role: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: string,
    voter: AddressLike,
    voterUserId: string,
    inFavor: boolean,
    weight: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    voter: string,
    voterUserId: string,
    inFavor: boolean,
    weight: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    voter: string;
    voterUserId: string;
    inFavor: boolean;
    weight: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceRegistry;
  waitForDeployment(): Promise<this>;

  interface: GovernanceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assignRole: TypedContractMethod<
    [account: AddressLike, userId: string, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      proposalId: string,
      contentHash: string,
      proposerUserId: string,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  elder: TypedContractMethod<[], [string], "view">;

  elderVoteWeight: TypedContractMethod<[], [bigint], "view">;

  finalizeProposal: TypedContractMethod<
    [proposalId: string],
    [void],
    "nonpayable"
  >;

  getProposal: TypedContractMethod<
    [proposalId: string],
    [GovernanceRegistry.ProposalStructOutput],
    "view"
  >;

  getRole: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  hasVoted: TypedContractMethod<
    [arg0: string, arg1: AddressLike],
    [boolean],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        proposalId: string;
        contentHash: string;
        proposerUserId: string;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  quorumThreshold: TypedContractMethod<[], [bigint], "view">;

  roles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalMembers: TypedContractMethod<[], [bigint], "view">;

  totalProposals: TypedContractMethod<[], [bigint], "view">;

  transferEldership: TypedContractMethod<
    [newElder: AddressLike],
    [void],
    "nonpayable"
  >;

  userIds: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  veto: TypedContractMethod<
    [proposalId: string, reason: string],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [proposalId: string, inFavor: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [account: AddressLike, userId: string, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      proposalId: string,
      contentHash: string,
      proposerUserId: string,
      deadline: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "elder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "elderVoteWeight"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "finalizeProposal"
  ): TypedContractMethod<[proposalId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: string],
    [GovernanceRegistry.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<[arg0: string, arg1: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        proposalId: string;
        contentHash: string;
        proposerUserId: string;
        votesFor: bigint;
        votesAgainst: bigint;
        createdAt: bigint;
        deadline: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quorumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "roles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMembers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalProposals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferEldership"
  ): TypedContractMethod<[newElder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userIds"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "veto"
  ): TypedContractMethod<
    [proposalId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [proposalId: string, inFavor: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EldershipTransferred"
  ): TypedContractEvent<
    EldershipTransferredEvent.InputTuple,
    EldershipTransferredEvent.OutputTuple,
    EldershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalApproved"
  ): TypedContractEvent<
    ProposalApprovedEvent.InputTuple,
    ProposalApprovedEvent.OutputTuple,
    ProposalApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalFinalized"
  ): TypedContractEvent<
    ProposalFinalizedEvent.InputTuple,
    ProposalFinalizedEvent.OutputTuple,
    ProposalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalVetoed"
  ): TypedContractEvent<
    ProposalVetoedEvent.InputTuple,
    ProposalVetoedEvent.OutputTuple,
    ProposalVetoedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "EldershipTransferred(address,address,uint256)": TypedContractEvent<
      EldershipTransferredEvent.InputTuple,
      EldershipTransferredEvent.OutputTuple,
      EldershipTransferredEvent.OutputObject
    >;
    EldershipTransferred: TypedContractEvent<
      EldershipTransferredEvent.InputTuple,
      EldershipTransferredEvent.OutputTuple,
      EldershipTransferredEvent.OutputObject
    >;

    "ProposalApproved(string,uint256,uint256,uint256)": TypedContractEvent<
      ProposalApprovedEvent.InputTuple,
      ProposalApprovedEvent.OutputTuple,
      ProposalApprovedEvent.OutputObject
    >;
    ProposalApproved: TypedContractEvent<
      ProposalApprovedEvent.InputTuple,
      ProposalApprovedEvent.OutputTuple,
      ProposalApprovedEvent.OutputObject
    >;

    "ProposalCreated(string,string,string,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalFinalized(string,uint256)": TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;
    ProposalFinalized: TypedContractEvent<
      ProposalFinalizedEvent.InputTuple,
      ProposalFinalizedEvent.OutputTuple,
      ProposalFinalizedEvent.OutputObject
    >;

    "ProposalVetoed(string,string,uint256)": TypedContractEvent<
      ProposalVetoedEvent.InputTuple,
      ProposalVetoedEvent.OutputTuple,
      ProposalVetoedEvent.OutputObject
    >;
    ProposalVetoed: TypedContractEvent<
      ProposalVetoedEvent.InputTuple,
      ProposalVetoedEvent.OutputTuple,
      ProposalVetoedEvent.OutputObject
    >;

    "RoleAssigned(address,string,uint8,uint256)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "VoteCast(string,address,string,bool,uint256,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
