/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceRegistry } from "./GovernanceRegistry";
export * as factories from "./factories";
export { GovernanceRegistry__factory } from "./factories/GovernanceRegistry__factory";
